### ISSUE TITLE
How did you ensure causality with CCBAM?

### ISSUE THREAD

**Issue by seorim0** [alibabasglab/FRCRN#2]
hello!
I read your paper.
Thank you for doing such a great project.

I have a question for you regarding a complex convolutional block attention module (CCBAM).
The paper states that the proposed model is implemented to enable real-time processing, but CCBAM's channel attention requires averaging the entire frame. How did you ensure causality with CCBAM?
Did you make any special settings?

Please let me know if I'm wrong about anything.

thank you.
I'll wait for your reply.

**Comment by alibabasglab** [comment]
The mask is used for real-time implementation.

**Comment by seorim0** [comment]
Thank you for the answer!
Have a nice day~
